// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYxn30wpSwSN5WXQiERK4lpAQ3YCbfUFw',
    appId: '1:1005022992517:web:47c5bc9056555ca8b7f1ec',
    messagingSenderId: '1005022992517',
    projectId: 'portfolyo-30f15',
    authDomain: 'portfolyo-30f15.firebaseapp.com',
    storageBucket: 'portfolyo-30f15.appspot.com',
    measurementId: 'G-3XTC8YHM2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxsijeyHvx_vDtkBvsXCxg8VOkZtx6eUs',
    appId: '1:1005022992517:android:c2008874302733a2b7f1ec',
    messagingSenderId: '1005022992517',
    projectId: 'portfolyo-30f15',
    storageBucket: 'portfolyo-30f15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-em_7ano0_QTZIEf6z03Q-NvIfCN0BlU',
    appId: '1:1005022992517:ios:e73c4d4ed8650918b7f1ec',
    messagingSenderId: '1005022992517',
    projectId: 'portfolyo-30f15',
    storageBucket: 'portfolyo-30f15.appspot.com',
    iosClientId: '1005022992517-pl2r95vglkvn4oia6j0vb1b0uj5ln0u5.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalportfolio',
  );
}
